# Generated by Django 3.1.5 on 2021-05-05 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20210505_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='Confirmpassword1',
            new_name='Confirmpassword',
        ),
    ]
