# Generated by Django 3.1.4 on 2021-05-05 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_nanda'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Nanda',
        ),
    ]
