# Generated by Django 3.1.4 on 2021-05-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20210505_2030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agent',
            new_name='Consultancy',
        ),
    ]
