# Generated by Django 3.1.4 on 2021-05-05 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0009_auto_20210505_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultancy',
            name='Agentid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
