# Generated by Django 3.1.4 on 2021-05-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20210505_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdcour',
            name='Univname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
