# Generated by Django 3.1.4 on 2021-05-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_stdcour_univname'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdappli',
            name='agentmail',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
