# Generated by Django 3.1.5 on 2021-05-06 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0013_stdappli_agentmail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offerletter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Letter', models.FileField(upload_to='')),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
