# Generated by Django 3.1.5 on 2021-05-06 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0014_offerletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='Name',
            field=models.CharField(default=12, max_length=500),
            preserve_default=False,
        ),
    ]
