# Generated by Django 3.1.5 on 2021-05-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0015_offerletter_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Empname', models.CharField(max_length=50, null=True)),
                ('Empdesg', models.CharField(max_length=50, null=True)),
                ('Empphone', models.CharField(max_length=50, null=True)),
                ('Emppassword', models.FileField(null=True, upload_to='')),
                ('Empconfirmpassword', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
