# Generated by Django 3.1.5 on 2021-05-27 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0016_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='Empmail',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='Univmail',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Empconfirmpassword',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Emppassword',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
