# Generated by Django 3.1.5 on 2021-05-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0017_auto_20210527_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultancydetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cname', models.CharField(max_length=50)),
                ('Aid', models.CharField(max_length=500)),
                ('Aadd', models.CharField(max_length=500)),
                ('Email', models.EmailField(max_length=500)),
                ('Phonenumber', models.CharField(max_length=500)),
                ('Bname', models.CharField(max_length=500)),
                ('Accountnumber', models.CharField(max_length=500)),
                ('Branch', models.CharField(max_length=500)),
                ('Ifsccode', models.CharField(max_length=500)),
            ],
        ),
    ]
