# Generated by Django 3.1.5 on 2021-05-27 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0018_consultancydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultancydetails',
            name='Phonenumber',
        ),
    ]
