# Generated by Django 3.1.5 on 2021-05-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_remove_consultancydetails_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdappli',
            name='Coursename',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='stdappli',
            name='fee',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
