# Generated by Django 3.1.4 on 2021-05-29 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0022_stdappli_pstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coursecommision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Uniname', models.CharField(max_length=50, null=True)),
                ('Unimail', models.CharField(max_length=50, null=True)),
                ('Coursename', models.CharField(max_length=50, null=True)),
                ('Coursecurr', models.CharField(max_length=50, null=True)),
                ('Courseamo', models.CharField(max_length=50, null=True)),
                ('Coursecomm', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='com',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
