# Generated by Django 3.1.4 on 2021-06-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0025_addemployee'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerletter',
            name='rfd',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
