# Generated by Django 3.1.4 on 2021-06-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0026_offerletter_rfd'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdappli',
            name='rfdfile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
