# Generated by Django 3.1.4 on 2021-06-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0027_stdappli_rfdfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stdappli',
            name='enroll',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
