# Generated by Django 3.1.4 on 2021-06-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0028_stdappli_enroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Bdate',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Bdetail',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='Bname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='consultancy',
            name='Agentid',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='consultancy',
            name='Firstname',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='consultancydetails',
            name='Cname',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='coursecommision',
            name='Courseamo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coursecommision',
            name='Coursecomm',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coursecommision',
            name='Coursecurr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coursecommision',
            name='Coursename',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coursecommision',
            name='Unimail',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='coursecommision',
            name='Uniname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Amo',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Appauth',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Couover',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Courseapp',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Cri',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Curr',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Depname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Dur',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Sem',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Sem1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Sem2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='Type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='courses',
            name='com',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Empconfirmpassword',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Empdesg',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Empmail',
            field=models.EmailField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Empname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Emppassword',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Empphone',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Univmail',
            field=models.EmailField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Edate',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Edetails',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='Ename',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Agentid',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Agentmail',
            field=models.EmailField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Intdate',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Intgrading',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Intmarks',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Intname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Intqual',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Sscdate',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Sscgrading',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Sscmarks',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Sscname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Sscqual',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Unicname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Unidate',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Unigrading',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Unimarks',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Uniname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdacd',
            name='Uniqual',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdcour',
            name='Agentid',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdcour',
            name='Agentmail',
            field=models.EmailField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdcour',
            name='Applyingfor',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdcour',
            name='Date',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdcour',
            name='Univname',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdcour',
            name='pcoun1',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdcour',
            name='pcoun2',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdcour',
            name='pcoun3',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdcour',
            name='pcour4',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdcour',
            name='pcour5',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdcour',
            name='pcour6',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdind',
            name='Address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdind',
            name='Agentid',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdind',
            name='Agentmail',
            field=models.EmailField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdind',
            name='City',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdind',
            name='Country',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdind',
            name='Dateofbirth',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdind',
            name='Gender',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdind',
            name='Maritial',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdind',
            name='Nationality',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdind',
            name='Phonenumber',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdind',
            name='State',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdpro',
            name='Agentid',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdpro',
            name='Agentmail',
            field=models.EmailField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdpro',
            name='Overallscoreeng',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdpro',
            name='Testeng',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdpro',
            name='Urleng',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdpro',
            name='Yeareng',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdpro1',
            name='Agentid',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdpro1',
            name='Agentmail',
            field=models.EmailField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdpro1',
            name='Overallscoread',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdpro1',
            name='Testad',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdpro1',
            name='Urlad',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='stdpro1',
            name='Yearad',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univcon',
            name='Award',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univcon',
            name='Departments',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univcon',
            name='Face',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univcon',
            name='Features',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univcon',
            name='Insta',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univcon',
            name='Intakes',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univcon',
            name='Link',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univcon',
            name='Location',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univcon',
            name='Req',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univcon',
            name='Staff',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univcon',
            name='Students',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='About',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Campuses',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Departments',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Name',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Rank',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Type',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Web',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='univdetail',
            name='Year',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
