# Generated by Django 3.1.4 on 2021-06-05 08:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0029_auto_20210605_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancydetails',
            name='Rbody',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultancydetails',
            name='Rno',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
