# Generated by Django 3.0.6 on 2021-06-05 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0031_auto_20210605_1725'),
        ('portal', '0031_auto_20210605_1756'),
    ]

    operations = [
    ]
