# Generated by Django 3.1.4 on 2021-05-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20210505_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultancy',
            name='Agentid',
            field=models.CharField(default=12, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stdind',
            name='Agentid',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stdind',
            name='Agentmail',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
